[package]
name = "rescribe-read-bbcode"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "BBCode reader for rescribe"

[dependencies]
rescribe-core = { workspace = true }
rescribe-std = { workspace = true }
