[package]
name = "rescribe-read-csl-json"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rescribe-core = { path = "../../rescribe-core" }
rescribe-std = { path = "../../nodes/rescribe-std" }
