[package]
name = "rescribe-write-twiki"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "TWiki writer for rescribe"

[dependencies]
rescribe-core = { workspace = true }
rescribe-std = { workspace = true }
